name = "Anpu"
description = "A port of the Hugo Anubis theme"
license = "MIT"
homepage = "https://github.com/zbrox/anpu-zola-theme"
# The minimum version of Zola required
min_version = "0.11.0"
# An optional live demo URL
demo = "https://anpu-zola-theme.netlify.app"

# Any variable there can be overriden in the end user `config.toml`
# You don't need to prefix variables by the theme name but as this will
# be merged with user data, some kind of prefix or nesting is preferable
# Use snake_casing to be consistent with the rest of Zola
[extra]
anpu_date_format = "%e %B %Y"
anpu_menu_links = []

# The theme author info: you!
[author]
name = "Rostislav Raykov"
homepage = "https://zbrox.com"

# If this is porting a theme from another static site engine, provide
# the info of the original author here
[original]
author =  "mitrichius"
homepage = "https://github.com/mitrichius/hugo-theme-anubis"
repo = "https://github.com/mitrichius/hugo-theme-anubis"
