[package]
name = "release"
version = "0.1.0"
authors = ["Benoit Vermont <redwarp@gmail.com>"]
edition = "2021"

[dependencies]
anyhow = "1.0"
git2 = "0.13"
conventional_commits_next_version_lib = "0.3"
semver = "1.0"
regex = "1.6"
