name: Deploy website
on:
  push:
    branches:
      - 'website'
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/website'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Init policy
        run: echo -e '+++\ntitle = "Privacy policy"\npath = "privacy"\ntemplate = "page.html"\n+++\n' >> ./website/content/pages/privacy.md
        shell: bash
      - name: Copy policy
        run: cat ./docs/privacy.md >> ./website/content/pages/privacy.md
      - name: Build
        uses: shalzz/zola-deploy-action@v0.16.1
        env:
          BUILD_DIR: website
          BUILD_ONLY: true
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./website/public
  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
